### ISSUE TITLE
Can't install on Mac computer

### ISSUE THREAD

**Issue by powermanwxy** [nijel/enca#17] opened 2015-04-04 05:36 UTC
My system version is OS X 10.10.2.When I type make check ,it show me something is wrong:
XingyunWudeMacBook-Pro:enca-1.13 Xingyun$ make check
Making check in tools
/Applications/Xcode.app/Contents/Developer/usr/bin/make  check-am
make[2]: Nothing to be done for `check-am'.
Making check in script
make[1]: Nothing to be done for `check'.
Making check in lib
make[1]: Nothing to be done for `check'.
Making check in src
/Applications/Xcode.app/Contents/Developer/usr/bin/make  check-am
make[2]: Nothing to be done for `check-am'.
Making check in devel-docs
make[1]: Nothing to be done for `check'.
Making check in test
/Applications/Xcode.app/Contents/Developer/usr/bin/make  check-TESTS
PASS: ./test-lists.sh
PASS: ./test-long-texts.sh
PASS: ./test-convlist.sh
PASS: ./test-guess-short.sh
PASS: ./test-guess-stdin.sh
PASS: ./test-guess-utf8.sh
PASS: ./test-pP.sh
PASS: ./test-aliases.sh
PASS: ./test-empty.sh
PASS: ./test-convert-64.sh
PASS: ./test-convert-filter.sh
PASS: ./test-errors.sh
PASS: ./test-ENCAOPT.sh
PASS: ./test-default-cs.sh
PASS: ./test-external.sh
1,3c1,4
< n�por po�ouchl�ch �lut�ch ���an� p�ehlu�il i zu��c� ork�n
< n�por po�ouchl�ch �lut�ch ���an� p�ehlu�il i zu��c� ork�n
< n�por po�ouchl�ch �lut�ch ���an� p�ehlu�il i zu��c� ork�n
---
> nápor poťouchlých žlutých číňanů přehlušil i zuřící orkán
> nápor poťouchlých žlutých číňanů přehlušil i zuřící orkán
> nápor poťouchlých žlutých číňanů přehlušil i zuřící orkán
> �
FAIL: ./test-iconv.sh
SKIP: ./test-recode.sh
========================================
1 of 16 tests failed
(1 test was not run)
Please report to https://bugs.cihar.com/
========================================
make[2]: *** [check-TESTS] Error 1
make[1]: *** [check-am] Error 2
make: *** [check-recursive] Error 1

#So please help me to fix this ,thanks!

**Comment by nijel** [comment] 2015-04-07 09:55
Duplicate of #6

**Closed by nijel** 2015-04-07 09:55 UTC

**Comment by nijel** [comment] 2016-01-04 14:47
Version 1.17 is out with this fix, see https://blog.cihar.com/archives/2016/01/04/enca-117/.
